const Algorithm1ActionTypes = {
  TOGGLE_DROPDOWN1: "TOGGLE_DROPDOWN1",
  SET_ALGORITHM1: "SET_ALGORITHM1",
  UPDATE_FORMATTED_TIME1: "UPDATE_FORMATTED_TIME1",
  RESET_TIMER1: "RESET_TIMER1",
  INCREMENT_STEPS1: "INCREMENT_STEPS1",
  RESET_STEPS1: "RESET_STEPS1"
};

export default Algorithm1ActionTypes;
