const Algorithm2ActionTypes = {
  TOGGLE_DROPDOWN2: "TOGGLE_DROPDOWN2",
  SET_ALGORITHM2: "SET_ALGORITHM2",
  UPDATE_FORMATTED_TIME2: "UPDATE_FORMATTED_TIME2",
  RESET_TIMER2: "RESET_TIMER2",
  INCREMENT_STEPS2: "INCREMENT_STEPS2",
  RESET_STEPS2: "RESET_STEPS2"
};

export default Algorithm2ActionTypes;
