const GridActionTypes = {
  SET_GRID: "SET_GRID",
  INITIALIZE_GRID: "INITIALIZE_GRID",
  ADD_WALL: "ADD_WALL",
  RESET_GRID: "RESET_GRID",
  RESET_DISTANCES_AND_ISVISITED: "RESET_DISTANCES_AND_ISVISITED",
  SET_START_NODE: "SET_START_NODE",
  SET_FINISH_NODE: "SET_FINISH_NODE",
  SETTING_START_NODE: "SETTING_START_NODE",
  SETTING_FINISH_NODE: "SETTING_FINISH_NODE",
  DONE_SETTING_START_NODE: "DONE_SETTING_START_NODE",
  DONE_SETTING_FINISH_NODE: "DONE_SETTING_FINISH_NODE",
  SETTING_WALLS: "SETTING_WALLS",
  DONE_SETTING_WALLS: "DONE_SETTING_WALLS"
};

export default GridActionTypes;
